### ISSUE TITLE
Can't compile for termux

### ISSUE THREAD

**Issue by Pixelsuft** [nepx/halfix#26]
```sh
node makefile --cc gcc
```
![image1](https://user-images.githubusercontent.com/68371847/116026814-98d2b280-a67d-11eb-8608-fd96095bbc98.png)

```sh
gcc -v
```
![image2](https://user-images.githubusercontent.com/68371847/116026921-d6374000-a67d-11eb-91a3-18eed95e63ec.png)

**Comment by nepx** [comment]
I had this problem trying to compile on Android as well. If you're
using an ARM phone, you can comment out the int3 instructions
(https://github.com/nepx/halfix/search?q=int3). Int3 does nothing but
trigger a debug breakpoint (I implemented it here:
https://github.com/nepx/halfix/blob/master/src/cpu/decoder.c#L1604).

I use it as a GDB breakpoint, but evidently it's a hack that only
works on my system.

**Comment by Pixelsuft** [comment]
I fixed errors, but now I'm getting other error:
![image](https://user-images.githubusercontent.com/68371847/116188521-c12be100-a751-11eb-8f95-da237a871a66.png)
(I'm installed sdl and sdl2 packages in termux)

**Comment by nepx** [comment]
That's what I get for not using `pkg-config`.,, the build system is a
giant kludge at this point, all my fault.

You can get rid of `-lSDLmain` in makefile.js (line 39). In the WASM
version I prune it out, but I was not aware that Termux lacked a
SDLmain package too.

**Comment by Pixelsuft** [comment]
![image](https://user-images.githubusercontent.com/68371847/116340820-00b60400-a80a-11eb-8034-a8a212561943.png)
Looooooooooooooooooooooooooooooooooooooool

**Comment by Pixelsuft** [comment]
```
pkg install tigervnc sdl sdl2 -y
vncserver -geometry 640x480
export DISPLAY=":1"
./halfix -c path-to-config
```

**Comment by Pixelsuft** [comment]
I'm optiming halfix for termux on Saturday

**Comment by Pixelsuft** [comment]
![image](https://user-images.githubusercontent.com/68371847/116499611-ce260d00-a8d6-11eb-8554-d7c6fd811695.png)
No lags on slowest phone.
Fastest VM for android.
