### ISSUE TITLE
Possible bug in FPREM1 implementation

### ISSUE THREAD

**Issue by DCNick3** [nepx/halfix#6]
As far as I can tell there is typo:

https://github.com/nepx/halfix/blob/1d942ac9a49aa2ddedb2d2af5c00681b2b414fd1/src/cpu/fpu.c#L950

Usage of `flags` makes no sense here. Maybe `temp2 > 0` should be placed there (as it indicates that the remainder found is a partial one as far as I can tell).

**Comment by nepx** [comment]
Good catch! You're absolutely right. `temp2` holds the flags from `floatx80_ieee754_remainder`, and I guess I got confused and put `flags` (opcode flags, nothing to do with the remainder) instead. 

Thanks for reporting, it has been fixed.
